# Generated by Django 4.2.1 on 2023-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
