# Generated by Django 3.2.21 on 2023-09-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time_field', models.TimeField(auto_now=True)),
                ('person', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
